[project]
name = "my-agent"
created = "2025-11-04T18:39:39.702782"
framework_version = "0.3.8"

[cli]
version = "1.0.0"
command = "co create my-agent"
template = "minimal"

[agent]
address = "0xe5bd5ae9cb1560d329837760ec3ae37553fa717a277519eaf486143ef92eb241"
short_address = "0xe5bd...b241"
email = "0xe5bd5ae9@mail.openonion.ai"
email_active = false
created_at = "2025-11-04T18:39:39.702800"
algorithm = "ed25519"
default_model = "gpt-4o-mini"
max_iterations = 10
